# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('codetva', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.CharField(max_length=20)),
                ('produitun', models.CharField(max_length=200)),
                ('produitdeux', models.CharField(blank=True, max_length=200)),
                ('produittrois', models.CharField(blank=True, max_length=200)),
                ('produitquatre', models.CharField(blank=True, max_length=200)),
                ('produitcinq', models.CharField(blank=True, max_length=200)),
                ('produitsix', models.CharField(blank=True, max_length=200)),
                ('produitsept', models.CharField(blank=True, max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
    ]
